VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_BUILD = 0
VERSION_INFO = (VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD)
VERSION_STRING = " %d.%d.%d" % VERSION_INFO
AUTHOR_NAME = "Fab-admin"
AUTHOR_EMAIL = ""
APP_NAME = "{* app_name *}"
DESCRIPTION = "A skeleton of %s" % APP_NAME

__version__ = VERSION_INFO
